export default [
	{
		id: 1,
		image: require('../../images/allando.png'),
		name: 'Sós karamellás sajttorta',
		price: '990,-Ft',
		eggFree: true,
		sugarFree: false,
		milkFree: false,
		glutenFree: false,
		lactoseFree: true,
		new: true,
	},
	{
		id: 2,
		image: require('../../images/alkalmakra.png'),
		name: 'OREO-s Kinder szelet',
		price: '990,-Ft',
		eggFree: false,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
	},
	{
		id: 3,
		image: require('../../images/szezonalis.png'),
		name: 'Epres Milka tortaszelet',
		price: '990,-Ft',
		eggFree: false,
		sugarFree: false,
		milkFree: true,
		glutenFree: false,
		lactoseFree: false,
		new: false,
	},
	{
		id: 4,
		image: require('../../images/szezonalis.png'),
		name: 'Epres Milka tortaszelet',
		price: '990,-Ft',
		eggFree: false,
		sugarFree: false,
		milkFree: true,
		glutenFree: false,
		lactoseFree: false,
		new: false,
	},
]
