export default [
	{
		id: 1,
		image: require('./images/allando.png'),
		name: 'Gesztenyés krémes',
		price: 950,
		eggFree: false,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
	},
	{
		id: 2,
		image: require('./images/alkalmakra.png'),
		name: 'Somlói galuska szelet',
		price: 1050,
		eggFree: true,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
	},
	{
		id: 3,
		image: require('./images/szezonalis.png'),
		name: 'Aranygaluska szelet',
		price: 1050,
		eggFree: true,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
	},
	{
		id: 4,
		image: require('./images/szezonalis.png'),
		name: 'Oreo-s kinder szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 5,
		image: require('./images/szezonalis.png'),
		name: 'Kinder maxi king szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 6,
		image: require('./images/szezonalis.png'),
		name: 'Madártej szelet',
		price: 950,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 7,
		image: require('./images/szezonalis.png'),
		name: 'Sós karamellás sajttorta',
		price: 990,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 8,
		image: require('./images/szezonalis.png'),
		name: 'Túrógombóc torta',
		price: 950,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 9,
		image: require('./images/szezonalis.png'),
		name: 'Epres Milka torta',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 10,
		image: require('./images/szezonalis.png'),
		name: 'Snickers szelet',
		price: 1050,
		eggFree: false,
		sugarfree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 11,
		image: require('./images/szezonalis.png'),
		name: 'Mákos guba torta',
		price: 1050,
		eggFree: true,
		sugarfree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
	},
	{
		id: 12,
		image: require('./images/szezonalis.png'),
		name: 'Mozart szelet',
		price: 1050,
		eggFree: false,
		sugarfree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 13,
		image: require('./images/szezonalis.png'),
		name: 'Mozart szelet',
		price: 1050,
		eggFree: false,
		sugarfree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: false,
		new: false,
	},
	{
		id: 14,
		image: require('./images/szezonalis.png'),
		name: 'Zserbó szelet',
		price: 1050,
		eggFree: false,
		sugarfree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
	{
		id: 15,
		image: require('./images/szezonalis.png'),
		name: 'Pisztácia szelet',
		price: 1050,
		eggFree: false,
		sugarfree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
	},
]
