export default [
	{
		id: 1,
		image: require('./images/gesztenyes.jpeg'),
		name: 'Gesztenyés krémes',
		price: 950,
		eggFree: false,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
		calories: '305,6 kcal/34g ch',
		seasonal: false,
	},
	{
		id: 2,
		image: require('./images/somloi.jpeg'),
		name: 'Somlói galuska szelet',
		price: 1050,
		eggFree: true,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
		calories: '180,3 kcal/ 21,4 g ch',
		seasonal: false,
	},
	{
		id: 3,
		image: require('./images/aranygaluska.jpeg'),
		name: 'Aranygaluska szelet',
		price: 1050,
		eggFree: true,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
		calories: '205 kcal/27,2g ch',
		seasonal: false,
	},
	{
		id: 4,
		image: require('./images/oreokinder.jpeg'),
		name: 'Oreo-s kinder szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '232 kcal/20,9g ch',
		seasonal: false,
	},
	{
		id: 5,
		image: require('./images/kindermaxi.jpeg'),
		name: 'Kinder maxi king szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '213 kcal/ 23,9 g ch',
		seasonal: false,
	},
	{
		id: 6,
		image: require('./images/madartej.jpeg'),
		name: 'Madártej szelet',
		price: 950,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '157 kcal/12 g ch',
		seasonal: false,
	},
	{
		id: 7,
		image: require('./images/soskaramellas.jpeg'),
		name: 'Sós karamellás sajttorta',
		price: 990,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '329 kcal/ 39,1g ch',
		seasonal: false,
	},
	{
		id: 8,
		image: require('./images/turo.jpeg'),
		name: 'Túrógombóc torta',
		price: 950,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '150 kcal/10,4g ch',
		seasonal: false,
	},
	{
		id: 9,
		image: require('./images/epresmilka.jpeg'),
		name: 'Epres Milka torta',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '198 kcal/14 g ch',
		seasonal: false,
	},
	{
		id: 10,
		image: require('./images/snickers.jpeg'),
		name: 'Snickers szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '254,5 kcal/ 23,9g ch',
		seasonal: false,
	},
	{
		id: 11,
		image: require('./images/makos.jpeg'),
		name: 'Mákos guba torta',
		price: 1050,
		eggFree: true,
		sugarFree: true,
		milkFree: true,
		glutenFree: true,
		lactoseFree: false,
		new: false,
		calories: '191,5 kcal/19g ch',
		seasonal: true,
		tags: ['ŐSZ-TÉL'],
	},
	{
		id: 12,
		image: require('./images/mozart.jpeg'),
		name: 'Mozart szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '177 kcal/20g ch',
		seasonal: true,
		tags: ['ŐSZ-TÉL'],
	},
	{
		id: 13,
		image: require('./images/zserbo.jpeg'),
		name: 'Zserbó szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '201,4 kcal/23,8 g ch',
		seasonal: true,
		tags: ['ŐSZ-TÉL'],
	},
	{
		id: 14,
		image: require('./images/pisztacia.jpeg'),
		name: 'Pisztácia szelet',
		price: 1050,
		eggFree: false,
		sugarFree: true,
		milkFree: false,
		glutenFree: true,
		lactoseFree: true,
		new: false,
		calories: '164,8 kcal/ 20g ch',
		seasonal: true,
		tags: ['ŐSZ-TÉL'],
	},
]
